# --- CentralV specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: False #LOOK INTO THIS!!

runner: "episode"

#buffer_size: 8
#batch_size_run: 8
#batch_size: 8
buffer_size: 256
batch_size_run: 256
batch_size: 256


env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "actor_critic_learner"
critic_q_fn: "centralV"
critic_baseline_fn: "centralV"
critic_train_mode: "seq"
critic_train_reps: 1
#I am changing this from 1 to 1000 since I just want monte carlo returns and no central V (since central V is feed forward NN and
#cannot memorize past observations)
q_nstep: 1000  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
critic_fact: # False by default
no_last_actions: False
no_state: False

name: "centralV"
