# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: False

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

critic_fact: # no critic factorization
critic_mixing_embed_dim_0: 32
critic_mixing_embed_dim_1: 128
test_no_baseline: False #for testing COMA without baseline
test_v_baseline: False #for testing COMA with a state-value baseline
test_vm_baseline: False #for testing COMA with a state-value baseline obtained from marginalizing the actions
test_rq_baseline: False #for testing COMA with a baseline formed from a random selection of agent action pairs
test_maxq_baseline: False
pair_coma: False
fql_lambda: 0.25
include_last_act: False
q_network_size: 128

name: "coma_smac"
