# ---- Defaults for 4 agents hunting 1 stag and 1 hare in a 10x10 environment

env: "stag_hunt"

env_args:
    agent_obs: [2, 2]
    capture_terminal: True
    capture_conditions: [0, 1]  # Number of free fields available to [stag, hare] to be captured
    episode_limit: 100
    intersection_global_view: False
    intersection_unknown: False
    mountain_slope: 0.0  # Probability that an "up" action will not be executed (vanilla = 0.0)
    n_agents: 4
    n_hare: 1
    n_stags: 1
    observe_walls: False
    observe_ids: False
    observe_one_hot: False
    p_stags_rest: 0.0
    p_hare_rest: 0.0
    print_caught_prey: False
    reward_hare: 5
    reward_stag: 10
    reward_collision: 0.0
    reward_time: -0.1
    toroidal: False
    truncate_episodes: True
    world_shape: [6, 6]

t_max: 1510000
